print("Hello, world! Python is set up correctly 🎉")
name = input("What should I call you? ")
print(f"Nice to meet you, {name}! ")
print("This is a test branch practice run. ")
print("Now you've locked this into memory.  That's how you do it. ")